# Site Settings
title: Jekyll & Bootstrap 4
email: dmcdonald1982@gmail.com
description: >
  Jekyll & Bootstrap 4
baseurl: "/personal"
url: "http://dmcdonald1982.github.io"
twitter_username:
github_username:  dmcdonald1982
# Build Settings
sass:
  sass_dir:
include: ['_pages']
kramdown:
  input: GFM
